name: Build iOS
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'
      - name: Install EAS CLI
        run: npm install -g eas-cli
      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: npm install
      - name: Build on EAS
        run: eas build --platform ios --non-interactive --no-wait
